server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://database:5432/moviedb
    driver-class-name: org.postgresql.Driver
    username: movieuser
    password: moviepass
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours

cors:
  allowed-origins: http://localhost:3000,http://frontend:3000
